package com.ecommerce.sportyshoes.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import com.ecommerce.sportyshoes.exceptions.OrderNotFound;

@ControllerAdvice
public class OrderExceptionController {
	
	@ExceptionHandler(value = OrderNotFound.class)
	public ResponseEntity<Object> exception(OrderNotFound exception) {
		return new ResponseEntity<Object>(exception.getMessage(), HttpStatus.NOT_FOUND);
	}
}